site_name: Mirav T. Mehta
theme:
  name: material
  icon:
    logo : material/google-podcast
  palette:
    - scheme: slate
      toggle:
        icon: material/eye
        name: Switch to light mode

    - scheme: default
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
  features:
    - header.autohide
    # Navigation
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.sections
    # Search
    - search.suggest
    - search.highlight
    - search.share
    # Table of contents-TOC
    - toc.follow
    - content.tabs.link

extra:
  generator: true
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:mirav.mailme@gmail.com
      name: Email
    - icon: fontawesome/brands/linkedin-in
      link: https://linkedin.com/in/miravtmehta
      name: Linkedin
    - icon: fontawesome/brands/github
      link: https://github.com/miravtmehta
      name: Github

plugins:
  - blog:
      categories_name: "Tags: "
      categories_allowed:
        - All
        - Engineering
        - General
        - Leadership
        - Product
        - Productivity
        - Startups
      post_url_format: "{slug}"
      blog_toc: true
      post_excerpt: required
      archive: false
  - search
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - def_list
  - md_in_html
  - pymdownx.tabbed:
      slugify:
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  - pymdownx.tasklist:
      custom_checkbox: true

copyright: Copyright &copy; 2023 - 2024 | Mirav T. Mehta

